<body class="flex items-center justify-center h-screen bg-gray-100">

    <div class="text-center">
        <h1 class="text-3xl font-semibold text-center text-green-500 dark:text-green-400"><?php if($this->lang == 'eng'): ?>
                                                TASK ADDED SUCCESSFULLY!
                                            <?php elseif($this->lang == 'cat'): ?>
                                                TASCA CREADA CORRECTAMENT!
                                            <?php elseif($this->lang == 'esp'): ?>
                                                TAREA AÑADIDA CORRECTAMENTE!
                                            <?php endif; ?></h1>
        <p class="text-lg text-gray-600"><?php if($this->lang == 'eng'): ?>
                                                You will be automatically redirected to home page in  
                                            <?php elseif($this->lang == 'cat'): ?>
                                                Es redirigirà automàticament a la pàgina principal en 
                                            <?php elseif($this->lang == 'esp'): ?>
                                                Se redirigirá automaticamente a la página principal en 
                                            <?php endif; ?><span id="countdown">3</span><?php if($this->lang == 'eng'): ?>
                                                seconds...
                                            <?php elseif($this->lang == 'cat'): ?>
                                                segons...
                                            <?php elseif($this->lang == 'esp'): ?>
                                                segundos...
                                            <?php endif; ?></p>
    </div>

    <script>
    let countdownElement = document.getElementById('countdown');
    let countdownValue = 3;

    const countdownTimer = setInterval(() => {
        countdownValue--;
        countdownElement.textContent = countdownValue;

        if (countdownValue <= 0) {
            clearInterval(countdownTimer);
            window.location.href = "/Sprint3/DEVELOPERS/XaSe/web";
        }
    }, 1000);
</script>
</body>